DAISY_SETTINGS = {
    'SITE_TITLE': 'UJ Blockchain Admin',
    'SITE_HEADER': 'UJ Blockchain Admin',
    'INDEX_TITLE': 'Hi, welcome to your dashboard',
    'SITE_LOGO': '/static/img/logo.png',
    'EXTRA_STYLES': [
        '/static/daisyui.css',
    ],
    'EXTRA_SCRIPTS': [],
    'LOAD_FULL_STYLES': True,
    'SHOW_CHANGELIST_FILTER': True,
    'DONT_SUPPORT_ME': True,
    'DEFAULT_THEME': None,
    'DEFAULT_THEME_DARK': None,
    'SHOW_THEME_SELECTOR': True,
    'THEME_LIST': [
        {'name': 'Light', 'value': 'light'},
        {'name': 'Dark', 'value': 'dark'},
    ],
    'APPS_REORDER': {
        'user': {
            'icon': 'fa-solid fas fa-link',
            'name': 'Users',
            'hide': False,
            'divider_title': 'Auth',
            'priority': 10,
        },
        'auth': {
            'icon': 'fa-solid fas fa-users-cog',
            'name': 'Groups',
            'hide': False,
            'priority': 9,
        },
        'sites': {
            'icon': 'fa-solid fas fa-link',
            'name': 'Sites',
            'hide': False,
            'priority': 8,
        },
        'axes': {
            'icon': 'fa-solid fas fa-users-cog',
            'name': 'Security',
            'hide': False,
            'app': 'axes',
            'divider_title': 'Security',
            'priority': 6,
        },
        'otp_totp': {
            'icon': 'fa-solid fas fa-mobile',
            'name': 'OTP Device',
            'hide': False,
            'app': 'otp_totp',
            'priority': 5,
        },
        'otp_static': {
            'icon': 'fa-solid fas fa-tasks',
            'name': 'OTP Static',
            'hide': False,
            'app': 'otp_totp',
            'priority': 4,
        },
    },
}
