# Generated by Django 5.2.11 on 2026-02-06 08:59

import contact.models
import django.utils.timezone
import pgcrypto.fields
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.CharField(default=contact.models.generate_custom_id, editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('full_name', pgcrypto.fields.EncryptedCharField(charset='utf-8', check_armor=True, cipher='aes', versioned=False)),
                ('email', pgcrypto.fields.EncryptedEmailField(charset='utf-8', check_armor=True, cipher='aes', max_length=254, versioned=False)),
                ('message', pgcrypto.fields.EncryptedTextField(charset='utf-8', check_armor=True, cipher='aes', max_length=500, versioned=False)),
                ('date_received', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['-date_received'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalContact',
            fields=[
                ('id', models.CharField(db_index=True, default=contact.models.generate_custom_id, editable=False, max_length=20)),
                ('full_name', pgcrypto.fields.EncryptedCharField(charset='utf-8', check_armor=True, cipher='aes', versioned=False)),
                ('email', pgcrypto.fields.EncryptedEmailField(charset='utf-8', check_armor=True, cipher='aes', max_length=254, versioned=False)),
                ('message', pgcrypto.fields.EncryptedTextField(charset='utf-8', check_armor=True, cipher='aes', max_length=500, versioned=False)),
                ('date_received', models.DateTimeField(default=django.utils.timezone.now)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Contact',
                'verbose_name_plural': 'historical Contacts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
