# Generated by Django 6.0.3 on 2026-03-12 12:46

import contact.models
import django.db.models.deletion
import django.utils.timezone
import encrypted_fields.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.CharField(default=contact.models.generate_custom_id, editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('first_name', encrypted_fields.fields.EncryptedCharField(max_length=100)),
                ('last_name', encrypted_fields.fields.EncryptedCharField(max_length=100)),
                ('email', encrypted_fields.fields.EncryptedEmailField(max_length=254)),
                ('message', encrypted_fields.fields.EncryptedTextField(max_length=500)),
                ('date_received', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['-date_received'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalContact',
            fields=[
                ('id', models.CharField(db_index=True, default=contact.models.generate_custom_id, editable=False, max_length=20)),
                ('first_name', encrypted_fields.fields.EncryptedCharField(max_length=100)),
                ('last_name', encrypted_fields.fields.EncryptedCharField(max_length=100)),
                ('email', encrypted_fields.fields.EncryptedEmailField(max_length=254)),
                ('message', encrypted_fields.fields.EncryptedTextField(max_length=500)),
                ('date_received', models.DateTimeField(default=django.utils.timezone.now)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Contact',
                'verbose_name_plural': 'historical Contacts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
