# Generated by Django 5.2.11 on 2026-02-06 10:57

import pgcrypto.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='historicalcontact',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='contact',
            name='last_name',
            field=pgcrypto.fields.EncryptedCharField(charset='utf-8', check_armor=True, cipher='aes', default='', versioned=False),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='last_name',
            field=pgcrypto.fields.EncryptedCharField(charset='utf-8', check_armor=True, cipher='aes', default='', versioned=False),
        ),
    ]
