# Generated by Django 5.2.11 on 2026-02-06 18:14

import pgcrypto.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_rename_full_name_contact_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=pgcrypto.fields.EncryptedCharField(charset='utf-8', check_armor=True, cipher='aes', versioned=False),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='last_name',
            field=pgcrypto.fields.EncryptedCharField(charset='utf-8', check_armor=True, cipher='aes', versioned=False),
        ),
    ]
