# Generated by Django 5.2.11 on 2026-03-06 11:52

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_contact_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=encrypted_fields.fields.EncryptedEmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=encrypted_fields.fields.EncryptedCharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=encrypted_fields.fields.EncryptedCharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=encrypted_fields.fields.EncryptedTextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='email',
            field=encrypted_fields.fields.EncryptedEmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='first_name',
            field=encrypted_fields.fields.EncryptedCharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='last_name',
            field=encrypted_fields.fields.EncryptedCharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='message',
            field=encrypted_fields.fields.EncryptedTextField(max_length=500),
        ),
    ]
