# Generated by Django 5.2.11 on 2026-03-06 11:52

import contact.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityRegistration',
            fields=[
                ('id', models.CharField(default=contact.models.generate_custom_id, editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(help_text="User's email address", max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('faculty', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('year_of_study', models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year / Advanced Diploma'), ('postgrad', 'Postgraduate')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
