# Generated by Django 6.0.3 on 2026-04-13 12:14

import contact.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FewsRegistration',
            fields=[
                ('id', models.CharField(default=contact.models.generate_custom_id, editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('organization', models.CharField(max_length=255, verbose_name='Institution / Organization')),
                ('attendance_type', models.CharField(choices=[('in-person', 'In-Person'), ('online', 'YouTube Live')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('selected', 'Selected'), ('rejected', 'Rejected')], max_length=20)),
            ],
            options={
                'verbose_name': 'FEWS Registration',
                'verbose_name_plural': 'FEWS Registrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
