# Generated by Django 6.0.4 on 2026-04-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_fewsregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventEmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ujb', 'UJ Blockchain Event'), ('fews', 'CCFEWS Event')], max_length=50)),
                ('applied_subject', models.CharField(default='Application Received', max_length=255)),
                ('applied_message_text', models.TextField(help_text='Used when saving a single record. Use HTML like &lt;br&gt; or &lt;strong&gt;.             Use variables like {{ first_name }}, {{ last_name }}, {{ organization }}.', verbose_name='Applied Message (Single)')),
                ('applied_bulk_message_text', models.TextField(help_text="Used when updating multiple records via Admin Actions. Do not use personal variables here.             Start with a generic greeting like 'Hi there,' or 'Dear Applicant,'.", verbose_name='Applied Message (Bulk)')),
                ('selected_subject', models.CharField(default='You are Selected', max_length=255)),
                ('selected_message_text', models.TextField(help_text='Used when saving a single record. Use HTML like &lt;br&gt; or &lt;strong&gt;.             Use variables like {{ first_name }}, {{ last_name }}, {{ organization }}.', verbose_name='Selected Message (Single)')),
                ('selected_bulk_message_text', models.TextField(help_text="Used when updating multiple records via Admin Actions. Do not use personal variables here.             Start with a generic greeting like 'Hi there,' or 'Dear Applicant,'.", verbose_name='Selected Message (Bulk)')),
                ('rejected_subject', models.CharField(default='Application Update', max_length=255)),
                ('rejected_message_text', models.TextField(help_text='Used when saving a single record. Use HTML like &lt;br&gt; or &lt;strong&gt;.             Use variables like {{ first_name }}, {{ last_name }}, {{ organization }}.', verbose_name='Rejected Message (Single)')),
                ('rejected_bulk_message_text', models.TextField(help_text="Used when updating multiple records via Admin Actions. Do not use personal variables here.             Start with a generic greeting like 'Hi there,' or 'Dear Applicant,'.", verbose_name='Rejected Message (Bulk)')),
                ('group_link', models.URLField(blank=True, help_text='Optional link for groups (e.g., LinkedIn/WhatsApp).', null=True)),
                ('attachment', models.FileField(blank=True, help_text='Optional flyer or document to attach.', null=True, upload_to='email_flyers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Email Configuration',
                'verbose_name_plural': 'Email Configurations',
            },
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='event_type',
            field=models.CharField(blank=True, default='FEWS', editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fewsregistration',
            name='event_type',
            field=models.CharField(blank=True, default='UJB', editable=False, max_length=50, null=True),
        ),
    ]
