# Generated by Django 6.0.4 on 2026-04-22 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_eventemailconfig_eventregistration_event_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventemailconfig',
            name='applied_bulk_message_text',
        ),
        migrations.AddField(
            model_name='eventemailconfig',
            name='registration_end_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 22, 9, 21, 0, 222254, tzinfo=datetime.timezone.utc)),
        ),
    ]
