# Generated by Django 6.0.4 on 2026-04-22 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_remove_eventemailconfig_applied_bulk_message_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventemailconfig',
            name='registration_end_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 22, 13, 52, 46, 283089, tzinfo=datetime.timezone.utc)),
        ),
    ]
