# Generated by Django 6.0.4 on 2026-04-22 13:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_eventemailconfig_registration_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventemailconfig',
            name='registration_end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
