# Generated by Django 6.0.4 on 2026-04-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_eventemailconfig_registration_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='email',
            field=models.EmailField(help_text="User's email address", max_length=254),
        ),
    ]
