# Generated by Django 6.0.4 on 2026-05-07 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_alter_eventregistration_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='event_type',
            field=models.CharField(blank=True, default='UJB', editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fewsregistration',
            name='event_type',
            field=models.CharField(blank=True, default='FEWS', editable=False, max_length=50, null=True),
        ),
    ]
