# Generated by Django 6.0.5 on 2026-06-15 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_alter_eventregistration_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fewsregistration',
            name='attendance_type',
            field=models.CharField(choices=[('in-person', 'In-Person'), ('online', 'YouTube Live')], default='In-Person', max_length=20),
        ),
    ]
