# Generated by Django 6.0.6 on 2026-07-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_alter_fewsregistration_attendance_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='year_of_study',
            field=models.CharField(blank=True, choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year / Advanced Diploma'), ('postgrad', 'Postgraduate')], max_length=20, null=True),
        ),
    ]
