# Generated by Django 6.0.6 on 2026-08-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_alter_eventregistration_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='learning_path',
            field=models.CharField(choices=[('coding', 'Coding'), ('drag_drop', 'Drag & Drop')], default='coding', max_length=20),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='repository_link',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
