# Generated by Django 5.2.11 on 2026-03-06 11:52

import contact.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.CharField(default=contact.models.generate_custom_id, editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(error_messages={'unique': 'An application with this email already exists.'}, max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('faculty', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=150)),
                ('nationality', models.CharField(max_length=100)),
                ('year_of_study', models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year')])),
                ('ieee_membership', models.BooleanField(default=False)),
                ('saiee_membership', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
