# Generated by Django 6.0.3 on 2026-03-11 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilitator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='other_membership',
            field=models.CharField(default='', max_length=100),
        ),
    ]
