# Generated by Django 5.2.11 on 2026-03-06 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalusers',
            name='role',
        ),
        migrations.RemoveField(
            model_name='users',
            name='role',
        ),
    ]
